### ISSUE TITLE
Pretty JSON uses absolute paths while others use relative

### ISSUE THREAD

**Issue by DarrienG** [jRimbault/yadf#5]
Could the default output be set to use the absolute path as well? Or if that is too much of a breaking change, perhaps an option could be provided to specify if an absolute or relative path is desired?

Side note: Apologies for making all the issues. I really like this tool a lot, but if it's bothersome I can stop :sweat_smile:

**Comment by jRimbault** [comment]
I'm pretty sure that if you give `yadf` an absolute path you'll get absolute paths and respectively if you give a relative path you'll get relative path ? Independently of the chosen output format.

**Comment by DarrienG** [comment]
Ah you're right, apologies. This is a mistake on my end. I must have given an absolute path one time and a relative path the next. Thanks for the help!
